# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-Prompt
version:      0.13
version_from: lib/Term/Prompt.pm
installdirs:  site
requires:
    Term::ReadKey:                 1
    Text::Wrap:                    1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
